services:
  db:
    image: mysql:latest
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: txlforma
      MYSQL_DATABASE: txlforma
      MYSQL_PASSWORD: txlforma
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-ptxlforma"]
      interval: 5s
      retries: 10
      timeout: 5s

  api:
    image: kendinh1/txlforma:latest
    container_name: api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/txlforma
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: txlforma
    volumes:
      - api_uploads:/workspace/uploads/images

volumes:
  db_data:
  api_uploads:
